#ifndef LIBERRORLOGGER_GLOBAL_H
#define LIBERRORLOGGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBERRORLOGGER_LIBRARY)
#  define LIBERRORLOGGER_EXPORT Q_DECL_EXPORT
#else
#  define LIBERRORLOGGER_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBERRORLOGGER_GLOBAL_H
