#ifndef LIBERRORLOGER_GLOBAL_H
#define LIBERRORLOGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBERRORLOGER_LIBRARY)
#  define LIBERRORLOGER_EXPORT Q_DECL_EXPORT
#else
#  define LIBERRORLOGER_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBERRORLOGER_GLOBAL_H
